# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HazelcastCommandlineClient < Formula
  desc "Hazelcast Command-line Client Project"
  homepage "https://github.com/utku-caglayan/hazelcast-commandline-client"
  version "1.0.0-beta1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v1.0.0-beta1/hazelcast-commandline-client_1.0.0-beta1_Darwin_arm64.tar.gz"
      sha256 "e42ac1ff25531bff2de7ea3778cdc525ff0624db0329ceafa1eeec353732bec1"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v1.0.0-beta1/hazelcast-commandline-client_1.0.0-beta1_Darwin_x86_64.tar.gz"
      sha256 "e288962b2cf53d94a90e9db576e97b9df9a9ec12d2bf3c02ddaefd578e2672d9"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v1.0.0-beta1/hazelcast-commandline-client_1.0.0-beta1_Linux_arm64.tar.gz"
      sha256 "cacd273c96579b44805a5e5b8518c38fb78888048a558223a553d7568bc34af4"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v1.0.0-beta1/hazelcast-commandline-client_1.0.0-beta1_Linux_x86_64.tar.gz"
      sha256 "6cbe1e8822bae51a4eb5a31e8e165d1a702d0c31ab39894e9c4730469f9e409c"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  def post_install
    ohai "Example usages:
    * `hzc` - start an interactive shell 🚀
    * `hzc map --name my-map put --key hello --value world` - put entry into map"
        completion_warning = <<~EOS
          ⚠️  To have superior experience, enable autocompletion on Brew. ⚠️
          You need to enable autocompletion just once for Brew. If it is already enabled, you can skip this part.
          ▪ For Bash users:
            1) `brew install bash-completion` and follow the printed \"Caveats\" section. Example \"Caveats\" instructions:
               Add the following line to your ~/.bash_profile:
               # !! Note that paths may differ depending on your installation, so you should follow the Caveats section on your system.
               [[ -r \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\" ]] && . \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\"
            2) `source ~/.bash_profile`
          ▪ For Zsh users:
          Follow https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
        EOS
        print completion_warning
  end
end
